name: Validate Example NFO Files

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.xml'
      - '**.xsd'
      - '.github/workflows/validate-examples.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.xml'
      - '**.xsd'

jobs:
  validate-nfo-files:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml requests
    
    - name: Create validation script
      run: |
        cat > validate_examples.py << 'EOF'
        import os
        import sys
        from lxml import etree
        import requests
        from pathlib import Path
        import urllib.parse
        
        def validate_nfo_file(filepath):
            """Validate a single NFO file against its schema."""
            print(f"\nValidating: {filepath}")
            
            try:
                # Parse the XML file
                with open(filepath, 'rb') as f:
                    doc = etree.parse(f)
                
                # Get schema location
                root = doc.getroot()
                schema_location = root.get('{http://www.w3.org/2001/XMLSchema-instance}schemaLocation')
                
                if not schema_location:
                    print(f"  ❌ No xsi:schemaLocation attribute found")
                    return False
                
                # Extract schema URL
                parts = schema_location.split()
                if len(parts) >= 2:
                    schema_url = parts[1]
                else:
                    print(f"  ❌ Invalid xsi:schemaLocation format")
                    return False
                
                print(f"  📋 Schema URL: {schema_url}")
                
                # Download schema with custom resolver for includes
                response = requests.get(schema_url, timeout=30)
                response.raise_for_status()
                
                # Parse the schema with a custom resolver for includes
                parser = etree.XMLParser()
                parser.resolvers.add(GitHubSchemaResolver(schema_url))
                schema_doc = etree.fromstring(response.content, parser)
                
                # Create XMLSchema object
                schema = etree.XMLSchema(schema_doc)
                
                # Validate
                if schema.validate(doc):
                    print(f"  ✅ Valid NFO file")
                    return True
                else:
                    print(f"  ❌ Validation errors:")
                    for error in schema.error_log:
                        print(f"     Line {error.line}: {error.message}")
                    return False
                    
            except etree.XMLSyntaxError as e:
                print(f"  ❌ XML syntax error: {e}")
                return False
            except Exception as e:
                print(f"  ❌ Error: {e}")
                return False
        
        class GitHubSchemaResolver(etree.Resolver):
            """Resolver that loads schema includes from GitHub raw URLs."""
            def __init__(self, base_url):
                self.base_url = base_url
                super().__init__()
            
            def resolve(self, url, id, context):
                try:
                    # If it's a relative path, make it absolute based on the main schema URL
                    if not url.startswith(('http://', 'https://')):
                        base = self.base_url.rsplit('/', 1)[0]
                        resolved_url = f"{base}/{url}"
                    else:
                        resolved_url = url
                    
                    # Download the included schema
                    response = requests.get(resolved_url, timeout=30)
                    response.raise_for_status()
                    return self.resolve_string(response.content, context)
                except Exception as e:
                    print(f"  ⚠️  Warning: Could not resolve include {url}: {e}")
                    return None
        
        def main():
            # Find all XML example files
            example_files = []
            for pattern in ['*.xml', 'examples/*.xml', 'Examples/*.xml']:
                example_files.extend(Path('.').glob(pattern))
            
            if not example_files:
                print("No example XML files found!")
                return 1
            
            print(f"Found {len(example_files)} example files to validate")
            
            # Validate each file
            failed_files = []
            for filepath in example_files:
                if not validate_nfo_file(str(filepath)):
                    failed_files.append(str(filepath))
            
            # Summary
            print("\n" + "="*60)
            print(f"Total files: {len(example_files)}")
            print(f"✅ Valid: {len(example_files) - len(failed_files)}")
            print(f"❌ Invalid: {len(failed_files)}")
            
            if failed_files:
                print("\nFailed files:")
                for filepath in failed_files:
                    print(f"  - {filepath}")
                return 1
            else:
                print("\n🎉 All example files are valid!")
                return 0
        
        if __name__ == "__main__":
            sys.exit(main())
        EOF
    
    - name: Validate example NFO files
      run: python validate_examples.py

  validate-schema-integrity:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install xmllint
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils
    
    - name: Validate XSD schemas
      run: |
        echo "Validating XSD schema files..."
        for xsd in Schemas/*.xsd main.xsd; do
          echo -n "Validating $xsd... "
          if xmllint --noout "$xsd" 2>/dev/null; then
            echo "✅ Valid"
          else
            echo "❌ Invalid"
            xmllint --noout "$xsd"
            exit 1
          fi
        done